"""empty message

Revision ID: 15c502c3e24f
Revises: cad988284953
Create Date: 2019-07-21 20:10:00.637783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15c502c3e24f'
down_revision = 'cad988284953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_ended', sa.DateTime(), nullable=True),
    sa.Column('sign_student', sa.Boolean(), nullable=True),
    sa.Column('sign_tutor', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('student', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tutor', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['student'], ['students.student_uuid'], ),
    sa.ForeignKeyConstraint(['tutor'], ['tutors.tutor_uuid'], ),
    sa.PrimaryKeyConstraint('id', 'summary_uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('summary_uuid')
    )
    op.add_column('students', sa.Column('status_login', sa.Boolean(), nullable=True))
    op.drop_column('students', 'status')
    op.add_column('tutors', sa.Column('activation', sa.Boolean(), nullable=True))
    op.add_column('tutors', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('tutors', sa.Column('status_login', sa.Boolean(), nullable=True))
    op.drop_column('tutors', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tutors', 'status_login')
    op.drop_column('tutors', 'experience')
    op.drop_column('tutors', 'activation')
    op.add_column('students', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('students', 'status_login')
    op.drop_table('summaries')
    # ### end Alembic commands ###
