"""empty message

Revision ID: 38b243c0bc89
Revises: 4ed4c76c24a4
Create Date: 2019-07-21 21:17:16.171308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b243c0bc89'
down_revision = '4ed4c76c24a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('time_reactivated', sa.DateTime(), nullable=True))
    op.add_column('tutors', sa.Column('time_tutor_off', sa.DateTime(), nullable=True))
    op.add_column('tutors', sa.Column('time_tutor_on', sa.DateTime(), nullable=True))
    op.add_column('tutors', sa.Column('time_unactivated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'time_unactivated')
    op.drop_column('tutors', 'time_tutor_on')
    op.drop_column('tutors', 'time_tutor_off')
    op.drop_column('tutors', 'time_reactivated')
    # ### end Alembic commands ###
