"""empty message

Revision ID: a830d4e37073
Revises: e5c008e1639f
Create Date: 2019-07-21 11:06:53.832827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a830d4e37073'
down_revision = 'e5c008e1639f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring',
    sa.Column('tutor_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('student_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['student_uuid'], ['students.student_uuid'], ),
    sa.ForeignKeyConstraint(['tutor_uuid'], ['tutors.tutor_uuid'], )
    )
    op.add_column('subjects', sa.Column('tutor', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'subjects', 'tutors', ['tutor'], ['tutor_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'tutor')
    op.drop_table('tutoring')
    # ### end Alembic commands ###
