"""empty message

Revision ID: b6094872c96b
Revises: cc1eda18b287
Create Date: 2019-07-17 23:50:11.319933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6094872c96b'
down_revision = 'cc1eda18b287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subjects', ['subject_uuid'])
    op.create_unique_constraint(None, 'subjects', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    # ### end Alembic commands ###
