"""empty message

Revision ID: cad988284953
Revises: 877287764bbd
Create Date: 2019-07-21 11:41:00.815459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cad988284953'
down_revision = '877287764bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name_subject', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('tutor', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['tutor'], ['tutors.tutor_uuid'], ),
    sa.PrimaryKeyConstraint('id', 'subject_uuid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('subject_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
